---
  - set_fact: log_dir="./"
    when: log_dir is undefined
    
  - name: "set fio type"
    set_fact:
      fio_type: file
    when: dbca == 'single' or storage_type == 'nfs' or storage_type == 'nfs-managed'

  - name: "set fio type"
    set_fact:
      fio_type: raw
    when: fio_type is undefined

  - name: "set fio target"
    set_fact:
      fio_target: "{{ ORA_DATA }}/fio.img"
    when: fio_type == 'file'

  - name: "set fio target"
    set_fact:
      fio_target: "{{ VOTE_DEV }}"
    when: fio_type == 'raw'

  - name: "create oradata"
    become: yes
    file:
      path: "{{ ORA_DATA }}"
      state: directory
      owner: grid
      group: oinstall
      mode: 0755
    when: fio_type == 'file' and inventory_hostname == groups["dbserver"][0]

  - name: "install fio packages"
    become: yes
    dnf: 
      name: fio
      state: present
    when: inventory_hostname == groups["dbserver"][0]

  - name: "execute fio"
    become: yes
    shell: "fio -filename={{ fio_target }}  -direct=1 -rw={{ item }} -bs=4k -size=2G -numjobs=64 -runtime=10 -group_reporting -name=fio.{{ item }} --output=/tmp/fio_{{ item }}.log"
    when: inventory_hostname == groups["dbserver"][0]
    with_items:
      - read
      - write
      - randread
      - randwrite

  - name: Remove file
    become: yes
    file:
      path: "{{ fio_target }}"
      state: absent
    when: fio_type == 'file' and inventory_hostname == groups["dbserver"][0]
    
  - name: "init dev"
    become: yes
    shell: "dd if=/dev/zero of={{ fio_target }} bs=1024k count=1000"
    when: fio_type == 'raw' and inventory_hostname == groups["dbserver"][0]

  - name: fetch fio.log
    become: yes
    fetch:
      src: "/tmp/fio_{{ item }}.log"
      dest: "{{ log_dir }}/fio"
    when: inventory_hostname == groups["dbserver"][0]
    with_items:
      - read
      - write
      - randread
      - randwrite
