  - name: "nmcli ipv4.dns"
    become: yes
    shell: nmcli con mod "{{ DNS_CON }}" ipv4.dns-search "{{ DOMAIN_NAME }}"

  - name: "nmcli reload"
    become: yes
    shell: nmcli con up "{{ DNS_CON }}"

  - name: "add /etc/hosts"
    become: yes
    lineinfile:
      path: /etc/hosts
      line: '{{ hostvars[host]['public_IP'] }} {{ hostvars[host]['NODENAME'] }}.{{ DOMAIN_NAME }} {{ hostvars[host]['NODENAME'] }}'
    with_items:
      - "{{ play_hosts }}"
