---      
  - name: "install selinux,firewalld"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - selinux-policy
      - firewalld
    when: ansible_distribution_version|int == 7
    tags:
      - security

  - name: "install selinux,firewalld"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - selinux-policy
      - iptables
    when: ansible_distribution_version|int == 6
    tags:
      - security

  - name: "disable selinux"
    become: yes
    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=disabled'
    tags:
      - security

  - name: "disable selinux setenforce"
    become: yes
    shell: setenforce 0
    ignore_errors: yes
    tags:
      - security

  - name: "disable firewalld"
    become: yes
    systemd: name="{{ item }}" state=stopped enabled=no
    with_items:
      - firewalld.service
    when: ansible_distribution_version|int == 7
    ignore_errors: yes
    tags:
      - security

  - name: "disable firewalld"
    become: yes
    service: name="{{ item }}" state=stopped enabled=no
    with_items:
      - iptables
    when: ansible_distribution_version|int == 6
    ignore_errors: yes
    tags:
      - security
      
  - name: "enable firewalld"
    become: yes
    systemd: name="{{ item }}" state=started enabled=yes
    with_items:
      - firewalld.service
    when: ansible_distribution_version|int == 7 and link_local is defined
    ignore_errors: yes
    tags:
      - security
      
  - name: "firewalld trusted vxlan_dev"
    become: yes
    firewalld: zone=public interface="{{ VXLAN_DEV }}" permanent=true state=enabled
    when: ansible_distribution_version|int == 7 and link_local is defined
    ignore_errors: yes
    tags:
      - security

  - name: "drop 169.254.169.254"
    become: yes
    firewalld: zone=drop source=169.254.169.254/32 permanent=true state=enabled
    when: ansible_distribution_version|int == 7 and link_local is defined
    ignore_errors: yes
    tags:
      - security
