---      
  - name: "install selinux,firewalld"
    become: yes
    dnf:
      name:
        - selinux-policy
        - selinux-policy-targeted
        - firewalld
      state: present
    tags:
      - security

#  - name: "disable selinux"
#    become: yes
#    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=disabled'
#    tags:
#      - security

#  - name: "disable selinux setenforce"
#    become: yes
#    shell: setenforce 0
#    ignore_errors: yes
#    tags:
#      - security

  - name: "firewalld allow vxlan"
    become: yes
    firewalld:
      port: 8472/udp
      permanent: yes
      state: enabled
    ignore_errors: yes
    tags:
      - security

  - name: "firewalld allow vnc"
    become: yes
    firewalld:
      port: 5901-5903/tcp
      permanent: yes
      state: enabled
    ignore_errors: yes
    tags:
      - security

  - name: "firewalld trusted vxlan_dev"
    become: yes
    firewalld:
      zone: trusted
      interface: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
     - vxlan0
     - vxlan1
     - vxlan2
    ignore_errors: yes
    tags:
      - security

#  - name: "drop 169.254.169.254"
#    become: yes
#    shell: "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 1 -m state --state NEW -m tcp -p tcp -d 169.254.169.254/32 -j REJECT;firewall-cmd --reload"
#    when: link_local is defined
#    ignore_errors: yes
#    tags:
#      - security

  - name: "drop 169.254.169.254"
    become: yes
    firewalld:
      rich_rule: rule family=ipv4 destination address=169.254.169.254/32 reject
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
    when: link_local is defined
    ignore_errors: yes
    tags:
      - security
