---
  - name: "copy 09_vxlan"
    become: yes
    copy: src=09_vxlan.j2 dest=/etc/NetworkManager/dispatcher.d/09_vxlan owner=root group=root mode=0700
    tags:
      - vxlan_conf
      



  - name: "install vxlan.init"
    become: yes
    shell: chdir=/usr/local/bin install -o root -g root -m 755 vxlan.init /etc/init.d/vxlan
    when: ansible_distribution_version|int == 6
    tags:
      - vxlan_init
      - vxlan_conf
      - addclient

  - name: "daemon_reload"
    become: yes
    systemd: daemon_reload=yes
    when: ansible_distribution_version|int == 7
    tags:
      - vxlan_init
      - vxlan_conf
      - addclient
      
  - name: "start_enable vxlan.service(Without NetworkManager)"
    become: yes
    systemd: name=vxlan.service state=started enabled=yes
    when: ansible_distribution_version|int == 7
    tags:
      - vxlan_init
      - vxlan_conf
      - addclient
      
  - name: "restart vxlan"
    become: yes
    shell: "chkconfig vxlan on;service vxlan restart"
    when: ansible_distribution_version|int == 6
    tags:
      - vxlan_init
      - vxlan_conf
      - addclient

