---
  - name: "firewalld allow vxlan"
    become: yes
    firewalld:
      zone: public
      port: 8472/udp
      permanent: yes
      state: enabled
      immediate: yes
    ignore_errors: yes
    tags:
      - vxlan_conf

  - name: "firewalld trusted vxlan_dev"
    become: yes
    firewalld:
      source: "{{ item }}/24"
#      interface: "{{ item }}"
      zone: trusted
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
     - "{{ vxlan0_NETWORK }}"
     - "{{ vxlan1_NETWORK }}"
     - "{{ vxlan2_NETWORK }}"
#     - vxlan0
#     - vxlan1
#     - vxlan2
    ignore_errors: yes
    tags:
      - vxlan_conf

  - name: "copy 09_vxlan"
    become: yes
    template:
      src: 09_vxlan.j2
      dest: /etc/NetworkManager/dispatcher.d/09_vxlan
      owner: root
      group: root
      mode: 0700
    tags:
      - vxlan_conf
    
  - name: "nmcli add vxlan"
    become: yes
    shell: "nmcli connection add type vxlan id {{ item.id }} con-name {{ item.name }} ifname {{ item.name }} dev {{ VXLAN_DEV }} remote 127.0.0.1 ip4 {{ item.ip }}/24"
    args:
      creates: "/etc/NetworkManager/system-connections/{{ item.name }}.nmconnection"
    with_items:
      - { name: vxlan0, id: 10, ip: "{{ vxlan0_IP }}" }
      - { name: vxlan1, id: 11, ip: "{{ vxlan1_IP }}" }
      - { name: vxlan2, id: 12, ip: "{{ vxlan2_IP }}" } 
    tags:
      - vxlan_conf
      
  - name: "nmcli up vxlan"
    become: yes
    shell: "nmcli con up {{ item }}"
    with_items:
      - vxlan0
      - vxlan1
      - vxlan2
    tags:
      - vxlan_conf
