---
  - name: "copy cvu"
    become: yes
    become_user: grid
    unarchive:
      src: "/media/{{ CVU_MEDIA }}"
      dest: "/tmp"
    when: inventory_hostname == groups["dbserver"][0]

  - name: "cvu"
    become: yes
    become_user: grid
    #shell: "{{ GRID_ORACLE_HOME }}/runcluvfy.sh stage -pre crsinst -n {% for host in groups['dbserver']  %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    shell: "/tmp/bin/cluvfy stage -pre crsinst -n {% for host in groups['dbserver']  %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %} -verbose"
    register: cvu_result
    ignore_errors: True
    when: inventory_hostname == groups["dbserver"][0]
      
  - debug: var=cvu_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]

  - name: "cvu_ssa"
    become: yes
    become_user: grid
    shell: "/tmp/bin/cluvfy comp ssa -n {% for host in groups['dbserver']  %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %} -s {{ VOTE_DEV }} -verbose"
    register: cvussa_result
    ignore_errors: True
    when: inventory_hostname == groups["dbserver"][0]
      
  - debug: var=cvussa_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
