---
  - name: "set IPERF_DEV"
    set_fact:
      IPERF_DEV: 'vxlan0'
    when: dbca != 'single'

  - name: "set IPERF_DEV"
    set_fact:
      IPERF_DEV: "{{ VXLAN_DEV }}"
    when: dbca == 'single'  

  - set_fact: log_dir="./"
    when: log_dir is undefined
    
  - name: re gather_facts for vxlan
    become: yes
    setup:
    ignore_errors: yes

  - name: "install iperf3"
    become: yes
    dnf: 
      name: iperf3
      state: present

  - name: "firewalld allow iperf"
    become: yes
    firewalld:
      zone: public
      port: 5201/tcp
      permanent: yes
      state: enabled
      immediate: yes
    ignore_errors: yes
    when: IPERF_DEV != "vxlan0"

  - name: start server iperf
    become: yes
    shell: iperf3 --server --one-off --daemon
    when: inventory_hostname == groups["dbserver"][0]

  - name: client iperf
    become: yes
    shell: iperf3 --client {{ hostvars[groups['dbserver'][0]]["ansible_" + IPERF_DEV]['ipv4']['address'] }} --time 60 --logfile /tmp/iperf.log
    when: "'dbserver' not in group_names"
    #when: inventory_hostname == groups["storage"][0]
    register: iperf_result


  - debug: var=iperf_result.stdout_lines
    when: "'dbserver' not in group_names"
    #when: inventory_hostname == groups["storage"][0]


  - name: fetch iperf.log
    become: yes
    fetch:
      src: "/tmp/iperf.log"
      dest: "{{ log_dir }}/iperf"
    when: "'dbserver' not in group_names"

