---
  - name: "install iperf3"
    become: yes
    dnf: 
      name: iperf3
      state: present
    tags:
      - iperf

  - name: "accept from client"
    become: yes
    firewalld:
      rich_rule: rule family=ipv4 destination address={{ hostvars[groups['client'][0]]["ansible_" + IPERF_DEV]['ipv4']['address'] }} accept
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
    when: inventory_hostname == groups["dbserver"][0] and IPERF_DEV != "vxlan0"
    ignore_errors: yes
    tags:
      - iperf

  - name: "accept from server"
    become: yes
    firewalld:
      rich_rule: rule family=ipv4 destination address={{ hostvars[groups['dbserver'][0]]["ansible_" + IPERF_DEV]['ipv4']['address'] }} accept
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
    when: inventory_hostname == groups["client"][0] and IPERF_DEV != "vxlan0"
    ignore_errors: yes
    tags:
      - iperf

  - name: start server iperf
    become: yes
    shell: iperf3 --server --one-off --daemon
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - iperf

  - name: client iperf
    become: yes
    shell: iperf3 --client {{ hostvars[groups['dbserver'][0]]["ansible_" + IPERF_DEV]['ipv4']['address'] }} --time 60
    when: inventory_hostname == groups["client"][0]
    register: iperf_result
    tags:
      - iperf

  - debug: var=iperf_result.stdout_lines
    when: inventory_hostname == groups["client"][0]
    tags:
      - iperf


