---
#https://www.server-world.info/query?os=CentOS_8&p=iscsi&f=2
  - name: "install iscsi-initiator-utils packages"
    become: yes
    dnf: 
      name: iscsi-initiator-utils
      state: present

  - name: create initiatorname.iscsi
    become: yes
    replace:
      path: /etc/iscsi/initiatorname.iscsi
      regexp: '^InitiatorName=(.*)'
      replace: 'InitiatorName={{ iSCSIName }}.{{ NODENAME }}'

  - name: Reboot
    become: yes
    reboot:
      reboot_timeout: 1200
    when: reboot_iscsi is defined

#iscsiadm start iscsid daemon automatically (not nessary systemctl enable iscsid)
  - name: "iscsiadm -m discovery"
    become: yes
    shell: "iscsiadm -m discovery -t sendtargets -p {{ STORAGE_SERVER }}"

  - name: "iscsiadm login"
    become: yes
    shell: "iscsiadm -m node --login"
      
      
