---
#https://www.server-world.info/query?os=CentOS_8&p=iscsi&f=1
#http://sugakun.blog.fc2.com/blog-entry-2.html

  - name: "install targetcli packages"
    become: yes
    dnf: 
      name: targetcli
      state: present

  - name: "create oradata"
    become: yes
    file:
      path: "{{ ORA_DATA }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: "create fileio"
    become: yes
    shell: "targetcli /backstores/fileio create {{ item.name }} {{ ORA_DATA }}/{{ item.name }}.img {{ item.size }}M"
    args:
      creates: "{{ ORA_DATA }}/{{ item.name }}.img"
    with_items:
      - { name: vote, size: "{{ VOTE_SIZE }}" }
      - { name: data, size: "{{ DATA_SIZE }}" }
      - { name: fra,  size: "{{ FRA_SIZE }}" } 

  - name: "create target"
    become: yes
    shell: "targetcli /iscsi create {{ TARGETNAME }}"
    ignore_errors: yes

  - name: "create luns"
    become: yes
    shell: "targetcli /iscsi/{{ TARGETNAME }}/tpg1/luns create /backstores/fileio/{{ item }}"
    with_items:
      - vote
      - data
      - fra
    ignore_errors: yes

  - name: "allow all"
    become: yes
    shell: "targetcli /iscsi/{{ TARGETNAME }}/tpg1 {{ item }}"
    with_items:
      - "set attribute authentication=0"
      - "set attribute generate_node_acls=1"
    ignore_errors: yes

  - name: "restart targetcli"
    become: yes
    systemd:
      name: target
      state: restarted 
      enabled: yes

  - name: "firewalld allow iscsi"
    become: yes
    firewalld:
      zone: public
      service: iscsi-target
      permanent: yes
      state: enabled
      immediate: yes
    ignore_errors: yes
