---
  - name: "dbca_cmd"
    set_fact:
      DBCA_CMD: "{{ ORA_ORACLE_HOME }}/bin/dbca -silent -createDatabase -templateName {{ TEMPLATENAME }} -gdbName {{ DBNAME }} -sid {{ SIDNAME }} policyManaged=true createServerPool=true serverPoolName={{ SERVERPOOLNAME }} -createAsContainerDatabase true -numberOfPDBs 1 -pdbName {{ PDBNAME }} -pdbAdminPassword {{ PDBADMINPASSWORD }} -SysPassword {{ SYSPASSWORD }} -SystemPassword {{ SYSTEMPASSWORD }} -emConfiguration NONE -redoLogFileSize {{ REDOFILESIZE }} -recoveryAreaDestination +{{ FRA_DISKGROUP_NAME }} -storageType ASM -asmSysPassword {{ ASMSYSPASSWORD }} -diskGroupName {{ DATA_DISKGROUP_NAME }} -characterSet {{ CHARSET }} -nationalCharacterSet {{ NCHAR }} -totalMemory {{ MEMORYTARGET }} -databaseType {{ DATABASETYPE }}"
    tags:
      - dbca
      - installdbca

  - name: "dbca serial"
    become: yes
    become_user: oracle
    shell: "{{ DBCA_CMD }} -nodelist {% for host in groups['dbserver'] %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    when: inventory_hostname == groups["dbserver"][0] and dbca == paralell
    tags:
      - dbca
      - installdbca


  - name: "delete database"
    become: yes
    become_user: oracle
    shell: "{{ ORA_ORACLE_HOME }}/bin/dbca -silent -deleteDatabase -sourceDB {{ DBNAME }} -sysDBAUserName sys -sysDBAPassword {{ SYSPASSWORD }}  -forceArchiveLogDeletion"
    when: inventory_hostname == groups["dbserver"][0] and dbca == delete
    tags:
      - dbcadelete

  - name: "crsctl"
    become: yes
    become_user: grid
    shell: "{{ GRID_ORACLE_HOME }}/bin/crsctl status resource -t"
    register: dbca_crsctl_result
    tags:
      - dbca
      - installdbca

  - debug: var=dbca_crsctl_result.stdout_lines
    tags:
      - dbca
      - installdbca
