---
  - set_fact: INSTALL_DB_OPS=""
    when: INSTALL_DB_OPS is undefined
    tags:
      - runinstallerdb
      - dbinstall
      - installdbca


  - name: "copy db media"
    become: yes
    become_user: oracle
    unarchive:
      src: "/media/{{ DB_MEDIA }}"
      dest: "{{ ORA_ORACLE_HOME }}"
      creates: "{{ ORA_ORACLE_HOME }}/bin"
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - creategridrsp
      - gridinstall
      - installdbca
      - download
      - downloaddb
      
  - name: "create db.rsp"
    become: yes
    template: 
      src: db.rsp.j2 
      dest: /home/oracle/db.rsp 
      owner: oracle 
      group: oinstall 
      mode: 0644
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - createdbrsp
      - dbinstall
      - installdbca

#30899722/30869156
  - name: "runInstaller(db)"
    become: yes
    become_user: oracle
    shell: "{{ ORA_ORACLE_HOME }}/runInstaller -silent -applyRU {{ MEDIA_PATH }}/{{ GRID_PATCH_NUM }} -responseFile /home/oracle/db.rsp -waitforcompletion {{ INSTALL_OPS }} {{ INSTALL_DB_OPS }}"
    when: inventory_hostname == groups["dbserver"][0]
    ignore_errors: True
    register: runinstallerdb_result
    tags:
      - runinstallerdb
      - dbinstall
      - installdbca

  - debug: var=runinstallerdb_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    failed_when: runinstallerdb_result.rc !=0 and runinstallerdb_result.rc != 250 and runinstallerdb_result.rc != 6
    tags:
      - runinstallerdb
      - dbinstall
      - installdbca

  - name: "db root.sh"
    become: yes
    shell: "{{ ORA_ORACLE_HOME }}/root.sh -silent"
    register: dbrootsh_result
    tags:
      - dbrootsh
      - dbinstall
      - installdbca

  - debug: var=dbrootsh_result.stdout_lines
    tags:
      - dbrootsh
      - dbinstall
      - installdbca

  - name: "disable dnfs"
    become: yes
    shell: "make -f ins_rdbms.mk ORACLE_HOME={{ ORA_ORACLE_HOME }} dnfs_off"
    args:
      chdir: "{{ ORA_ORACLE_HOME }}/rdbms/lib"
    when: DNFS is defined and DNFS == 'disable'
    tags:
      - dbrootsh
      - dbinstall
      - installdbca
      - oradisablednfs
