  - name: "executeConfigTools"
    become: yes
    become_user: grid
    shell: "{{ GRID_ORACLE_HOME }}/gridSetup.sh -executeConfigTools -responseFile /home/grid/grid.rsp -silent {{ INSTALL_OPS }}"
    register: asmca_result
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - execonfig
      - gridinstall
      - installdbca

  - debug: var=asmca_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - execonfig
      - gridinstall
      - installdbca

#  - name: "change css misscount"
#    become: yes
#    shell: "{{ GRID_ORACLE_HOME }}/bin/crsctl set css misscount 360"
#    when: inventory_hostname == groups["dbserver"][-1]
#    tags:
#      - runinstallergrid
#      - gridinstall
#      - installdbca


  - name: "create diskgroup"
    become: yes
    become_user: grid
    shell : "{{ GRID_ORACLE_HOME }}/bin/asmca -silent -createDiskGroup  -diskGroupName {{ item.name }} -disk {{ item.path }} -redundancy EXTERNAL -au_size 1"
    when: inventory_hostname == groups["dbserver"][0] and storage_type !='nbd'
    register: createdg_result
    with_items:
      - { name: "{{ DATA_DISKGROUP_NAME }}", path: "{{ DATA_DEV }}" }
      - { name: "{{ FRA_DISKGROUP_NAME }}", path: "{{ FRA_DEV }}" }
    tags:
      - gridinstall
      - createdg
      - installdbca
      
