---
#  - name: "firewalld allow vnc"
#    become: yes
#    firewalld:
#      zone: public
#      port: 5901-5903/tcp
#      permanent: yes
#      state: enabled
#      immediate: yes
#    ignore_errors: yes
#    tags:
#      - vnc

#  - name: install the 'Server With GUI' package group
#    become: yes
#    dnf:
#      name: '@Server with GUI'
#      state: present
#    tags:
#      - vnc

#https://bugzilla.redhat.com/show_bug.cgi?id=1782899
  - name: install the 'Server With GUI' package group
    become: yes
    shell: "dnf -y group install 'Server With GUI' --nobest && dnf -y group upgrade 'Server With GUI'"
    tags:
      - vnc
      
  - name: install tigervnc-server
    become: yes
    dnf:
      name: 'tigervnc-server'
      state: present
    tags:
      - vnc
      
  - name: Reboot
    become: yes
    reboot:
      reboot_timeout: 300
    tags:
      - vnc


#bash XXutil.sh ssh storage 6901 5901
#vncviewer localhost:6901
