---
#  - name: "firewalld allow vnc"
#    become: yes
#    firewalld:
#      zone: public
#      port: 5901-5903/tcp
#      permanent: yes
#      state: enabled
#      immediate: yes
#    ignore_errors: yes
#    tags:
#      - vnc

  - name: install the 'Server With GUI' package group
    become: yes
    dnf:
      name: '@Server with GUI'
      state: present
    tags:
      - vnc
 
  - name: install tigervnc-server
    become: yes
    dnf:
      name: 'tigervnc-server'
      state: present
    tags:
      - vnc
      
  - name: Reboot
    become: yes
    reboot:
      reboot_timeout: 300
    tags:
      - vnc
