---
  - set_fact: WindowManager="xfce"
    when: WindowManager is undefined
    tags:
      - vnc
      
  - name: "install epel"
    become: yes
    yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm" state=present
    when: WindowManager == "xfce"
    tags:
      - vnc

  - name: "dummy yum command (GPGKEY INSTALL)"
    become: yes
    shell: yum -y search nfs-utils
    ignore_errors: true
    tags:
      - vnc

  - name: "install gnome"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - "@^graphical-server-environment"
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    when: WindowManager == "gnome" 
    tags:
      - vnc

  - name: "install xfce"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - "@xfce-desktop"
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    when: WindowManager == "xfce"
    tags:
      - vnc
 
  - name: "install vnc,firefox,unzip,mesa-libGLU-devel"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - tigervnc-server
      - firefox
      - unzip
      - mesa-libGLU-devel
      - mesa-libEGL
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    tags:
      - vnc

  - name: Copy vnc service file
    become: yes
    shell: "cp /usr/lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@:{{item.0 + 1}}.service"
    with_indexed_items:
      - oracle
      - grid
    tags:
      - vnc

  - name: edit vnc service file
    become: yes
    shell: "sed -i -e 's/<USER>/{{ item.1 }}/g' /etc/systemd/system/vncserver@:{{item.0 + 1}}.service"
    with_indexed_items:
      - oracle
      - grid
    tags:
      - vnc

  - name: edit vnc service file
    become: yes
    shell: "sed -i -e 's/vncserver %i/vncserver -geometry 1024x768 -depth 16 %i/g' /etc/systemd/system/vncserver@:{{item.0 + 1}}.service"
    with_indexed_items:
      - oracle
      - grid
    tags:
      - vnc

  - name: "crete directory"
    become: yes
    file: path="/home/{{ item }}/.vnc" state=directory mode=0755 group=oinstall owner={{ item }}
    with_items:
      - oracle
      - grid
    tags:
      - vnc
      
  - name: "crete vncpasswd"
    become: yes
    shell: "echo {{ vnc_pass }} | vncpasswd -f > /home/{{ item }}/.vnc/passwd"
    with_items:
      - oracle
      - grid
    tags:
      - vnc
      
  - name: "chown vncpasswd"
    become: yes
    file: path="/home/{{ item }}/.vnc/passwd" mode=0600 group=oinstall owner={{ item }}
    with_items:
      - oracle
      - grid
    tags:
      - vnc


  - name: "copy xstartup"
    become: yes
    template: src=xstartup.j2 dest="/home/{{ item }}/.vnc/xstartup" mode=0755 owner={{ item }} group=oinstall
    with_items:
      - oracle
      - grid
    tags:
      - vnc

  - name: "daemon-reload"
    become: yes
    shell: systemctl daemon-reload
    tags:
      - vnc

  - name: start vnc service
    become: yes
    systemd: name="vncserver@:{{item.0 + 1}}.service" state=restarted enabled=yes
    with_indexed_items:
      - oracle
      - grid
    tags:
      - vnc

  - name: "crete download directory"
    become: yes
    file: path={{ MEDIA_PATH }} state=directory mode=0777 group=oinstall owner=oracle
    tags:
      - vnc

  - name: add sudoer
    become: yes
    lineinfile: dest=/etc/sudoers.d/{{ item }} line="{{ item }} ALL=(ALL) NOPASSWD:ALL" create=yes owner=root group=root mode=0440
    with_items:
      - oracle
      - grid
    tags:
      - vnc

