---
  - name: "install dnsmasq packages"
    become: yes
    dnf: 
      name: dnsmasq
      state: present
    tags:
      - dnsmasq

  - name: "create addn-hosts"
    become: yes
    template: src=addn-hosts.j2 dest=/etc/addn-hosts owner=root group=root mode=0644
    tags:
      - dnsmasq
      
  - name: "copy dnsmasq.conf"
    become: yes
    template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "copy resolv.dnsmasq.conf from /etc/resolv.conf"
    become: yes
    shell: cp /etc/resolv.conf /etc/resolv.dnsmasq.conf
      creates=/etc/resolv.dnsmasq.conf
    tags:
      - dnsmasq

  - name: "add  resolv.dnsmasq.conf"
    become: yes
    lineinfile: state=present create=yes insertafter=EOF line="nameserver {{ ADD_NAMESERVER }}" dest=/etc/resolv.dnsmasq.conf
    when: ADD_NAMESERVER is defined
    tags:
      - dnsmasq

  - name: "restart and  enable dnsmasq.service"
    become: yes
    systemd:
      state: restarted
      enabled: yes
      name: dnsmasq
    tags:
      - dnsmasq

  - name: "nmcli ipv4.ignore-auto-dns"
    become: yes
    shell: "nmcli con mod {{ VXLAN_DEV }} ipv4.ignore-auto-dns yes"
    tags:
      - dnsmasq

  - name: IPv4 DNS server addresses
    nmcli:
      conn_name: {{ VXLAN_DEV }} 
      type: ethernet
      dns4: 127.0.0.1
      state: present
    tags:
      - dnsmasq
