---
  - name: "set targe(HA)"
    set_fact:
      TARGET: "{{ SCAN_NAME }}"
    when: dbca != 'single'
    tags:
      - slob

  - name: "set target(SINGLE)"
    set_fact:
      TARGET:  '{{ hostvars[groups["dbserver"][0]]["ansible_" + VXLAN_DEV ].ipv4.address }}'
    when: dbca == 'single'  
    tags:
      - slob
      
  - name: "set db_create_file_dest"
    set_fact:
      db_create_file_dest: '+DATA'
    when: dbca != 'single'
    tags:
      - slob
      
  - name: "set db_create_file_dest"
    set_fact:
      db_create_file_dest:  '{{ ORA_DATA }}/{{ DBNAME }}'
    when: dbca == 'single'  
    tags:
      - slob

  - name: "create tnsnames.ora"
    template: 
      src: tnsnames.ora.j2 
      dest: "~/tnsnames.ora"
      mode: 0644
    tags:
      - slob

  - name: download slob
    unarchive:
      src: https://github.com/therealkevinc/SLOB_distribution/raw/master/2018.04.16.slob_2.4.2.1.tar.gz
      dest: "~/"
      remote_src: yes
      creates: "~/SLOB"
    tags:
      - slob

  - name: "install gcc"
    become: yes
    dnf:
      name: 
        - gcc
      state: latest
    tags:
      - slob
  
  - name: "make slob"
    shell: make
    args:
      chdir: "~/SLOB/wait_kit"
    tags:
      - slob

  - name: "copy slob.conf"
    template: 
      src: slob.conf.j2 
      dest: "~/SLOB/slob.conf"
      mode: 0644
    tags:
      - slob

  - name: create table
    shell:
      cmd: |
        export PATH={{ INSTANT_CLIENT_PATH }}/bin:$PATH
        export LD_LIBRARY_PATH={{ INSTANT_CLIENT_PATH }}/lib:$LD_LIBRARY_PATH
        export TNS_ADMIN=~/
        sqlplus 'sys/{{ SYSPASSWORD }}@{{ TARGET }}:1521/{{ DBNAME }} as sysdba' <<'EOF'
        alter session set db_create_file_dest='{{ db_create_file_dest }}';
        @misc/ts.sql
        exit
        EOF
    args:
      chdir: "~/SLOB"
    register: create_ts_result
    tags:
      - slob

  - debug: var=create_ts_result.stdout_lines
    tags:
      - slob
