---
  - name: "set db_create_file_dest"
    set_fact:
      db_create_file_dest: '+DATA'
    when: dbca != 'single'
    tags:
      - slob
      
  - name: "set db_create_file_dest"
    set_fact:
      db_create_file_dest:  '{{ ORA_DATA }}/{{ DB_NAME }}'
    when: dbca == 'single'  
    tags:
      - slob

  - name: download slob
    unarchive:
      src: https://github.com/therealkevinc/SLOB_distribution/raw/master/2018.04.16.slob_2.4.2.1.tar.gz
      dest: "~/"
      remote_src: yes
    tags:
      - slob

  - name: "install gcc"
    become: yes
    dnf:
      name: 
        - gcc
      state: latest
    tags:
      - slob
  
  - name: "make slob"
    shell: make
    args:
      chdir: "~/SLOB/wait_kit"
    tags:
      - slob
 
  - name: create table
    shell:
      cmd: |
        sqlplus 'sys/{{ SYSPASSWORD }}@{{ TARGET }}:1521/{{ DBNAME }} as sysdba' <<'EOF'
        alter session set db_create_file_dest='{{ db_create_file_dest }}';
        @misc/ts.sql

        exit
        EOF
    args:
      chdir: "~/"
    tags:
      - jdbcrunner
      - snapper
