---
  - name: "install dnsmasq packages"
    become: yes
    dnf: 
      name: dnsmasq
      state: present


  - name: "create addn-hosts"
    become: yes
    template:
      src: addn-hosts.j2
      dest: /etc/addn-hosts
      owner: root
      group: root
      mode: 0644

      
  - name: "copy dnsmasq.conf"
    become: yes
    template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644


  - name: "copy resolv.dnsmasq.conf from /etc/resolv.conf"
    become: yes
    shell: cp /etc/resolv.conf /etc/resolv.dnsmasq.conf
    args:
      creates: /etc/resolv.dnsmasq.conf


  - name: "add  resolv.dnsmasq.conf"
    become: yes
    lineinfile:
      state: present
      create: yes
      insertafter: EOF
      line: "nameserver {{ ADD_NAMESERVER }}"
      dest: /etc/resolv.dnsmasq.conf
    when: ADD_NAMESERVER is defined


  - name: "restart and  enable dnsmasq.service"
    become: yes
    systemd:
      state: restarted
      enabled: yes
      name: dnsmasq

  - name: "nmcli ipv4.ignore-auto-dns"
    become: yes
    shell: nmcli con mod "{{ DNS_CON }}" ipv4.ignore-auto-dns yes


  - name: "nmcli ipv4.dns"
    become: yes
    shell: nmcli con mod "{{ DNS_CON }}" ipv4.dns 127.0.0.1


  - name: "nmcli reload"
    become: yes
    shell: nmcli con up "{{ DNS_CON }}"

