---
  - name: "crsctl"
    become: yes
    become_user: grid
    shell: "{{ GRID_ORACLE_HOME }}/bin/crsctl status resource -t"
    register: crsctl_result
    tags:
      - crsctl
      - gridinstall
      - installdbca

  - debug: var=crsctl_result.stdout_lines
    tags:
      - crsctl
      - gridinstall
      - installdbca
