---
  - name: "create luns"
    become: yes
    shell: "/usr/lib/udev/scsi_id -g -u -d  {{ item }}"
    with_items:
      - "{{ RAW_VOTE_DEV }}"
      - "{{ RAW_DATA_DEV }}"
      - "{{ RAW_FRA_DEV }}"
    register: scsi_id_result
    ignore_errors: yes


