---      
  - name: "install selinux,firewalld"
    become: yes
    dnf:
      name:
 #       - selinux-policy
 #       - selinux-policy-targeted
        - firewalld
      state: present

#  - name: "disable selinux"
#    become: yes
#    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=disabled'
#    tags:
#      - misc

  - name: "disable selinux"
    become: yes
    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=permissive'
    
  - name: "disable selinux setenforce"
    become: yes
    shell: setenforce 0
    ignore_errors: yes
      
  - name: "firewalld trusted haip"
    become: yes
    firewalld:
      source: "{{ item }}"
      zone: trusted
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
     - "169.254.0.0/16"
     - "224.0.0.0/24"
    ignore_errors: yes

  - name: "enable firewalld logs"
    become: yes
    shell: "firewall-cmd --set-log-denied all;firewall-cmd --reload"
    ignore_errors: yes


  - name: "delete /etc/dhcp/dhclient.d/google_hostname.sh(for google)"
    become: yes
    file: 
      path: /etc/dhcp/dhclient.d/google_hostname.sh
      state: absent
    when: google_hostname is defined 
  
  - name: "change hostname"
    become: yes
    shell: "hostnamectl set-hostname {{ NODENAME }}.{{ DOMAIN_NAME }} --static"
    when: hostname_change is defined
    ignore_errors: yes

      
   
