---      
  - name: "install selinux,firewalld"
    become: yes
    dnf:
      name:
 #       - selinux-policy
 #       - selinux-policy-targeted
        - firewalld
      state: present
    tags:
      - misc

#  - name: "disable selinux"
#    become: yes
#    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=disabled'
#    tags:
#      - misc

  - name: "disable selinux"
    become: yes
    replace: dest='/etc/selinux/config' regexp='SELINUX=enforcing' replace='SELINUX=permissive'
    tags:
      - misc

  - name: "disable selinux setenforce"
    become: yes
    shell: setenforce 0
    ignore_errors: yes
    tags:
      - misc

  - name: "drop 169.254.169.254 from grid"
    become: yes
    shell: "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 1 -m owner --uid-owner grid -m state --state NEW -m tcp -p tcp -d 169.254.169.254/32 -j REJECT;firewall-cmd --reload"
    when: "link_local is defined and 'dbserver' in group_names"
    ignore_errors: yes
    tags:
      - misc

  - name: "firewalld trusted haip"
    become: yes
    firewalld:
      source: "169.254.0.0/16"
      zone: trusted
      permanent: yes
      state: enabled
      immediate: yes
    ignore_errors: yes
    tags:
      - misc

  - name: "enable firewalld logs"
    become: yes
    shell: "firewall-cmd --set-log-denied all;firewall-cmd --reload"
    ignore_errors: yes
    tags:
      - misc


  - name: "delete /etc/dhcp/dhclient.d/google_hostname.sh(for google)"
    become: yes
    file: 
      path: /etc/dhcp/dhclient.d/google_hostname.sh
      state: absent
    tags:
      - misc
  
  - name: "change hostname"
    become: yes
    shell: "hostnamectl set-hostname {{ NODENAME }}.{{ DOMAIN_NAME }} --static"
    when: hostname_change is defined
    ignore_errors: yes
    tags:
      - misc
      
      
