---
  - name: "install jdbcrunner dependency library"
    become: yes
    dnf:
      name:
        - git
        - ant
#        - java-1.7.0-openjdk-devel
      state: latest
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - installjdbcrunner

  - name: "create user"
    become: yes
    become_user: oracle
    script: createuser.sh "{{ SIDNAME }}1"
    when: inventory_hostname == groups["dbserver"][0]
    register: createuser_result
    tags:
      - jdbcrunner   

  - debug: var=createuser_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner
      
  - name:
    git:
      repo: https://github.com/sh2/jdbcrunner.git
      dest: "~/jdbcrunner"
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - installjdbcrunner

  - name: "unzip jdvcdriver"
    local_action: shell {{ UNZIP }} /media/{{ GRID_MEDIA }} {{ JDBCDRIVER }}
    args:
      creates: "/tmp/{{ JDBCDRIVER }}"
      executable: /bin/bash
      chdir: /tmp
    run_once: true
    when: inventory_hostname == groups["client"][0] and MEDIA_COPY is defined and MEDIA_COPY !=""
    tags:
      - jdbcrunner
      
  - name: "copy jdbcdriver"
    copy:
      src: "/tmp/{{ JDBCDRIVER }}"
      dest: "~/jdbcrunner/lib/ojdbc.jar"
    when: inventory_hostname == groups["client"][0] and MEDIA_COPY is defined and MEDIA_COPY !=""
    tags:
      - jdbcrunner

  - name: ant
    shell: /usr/bin/ant && touch ant.txt
    args:
      chdir: "~/jdbcrunner"
      creates: ant.txt
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - installjdbcrunner

  - name: load tpcc data
    shell: "/usr/bin/java -Djava.security.egd=file:/dev/./urandom -cp jdbcrunner-1.3-nojdbc.jar:lib/ojdbc.jar JR scripts/tpcc_load.js -jdbcDriver oracle.jdbc.driver.OracleDriver -jdbcUrl jdbc:oracle:thin:@{{ SCAN_NAME }}:1521/{{ PDBNAME }}"
    args:
      chdir: "~/jdbcrunner"
    when: inventory_hostname == groups["client"][0]
    register: tpccload_result
    tags:
      - jdbcrunner

  - debug: var=tpccload_result.stdout_lines
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner

  - name: exec tpcc
    shell: "/usr/bin/java -Djava.security.egd=file:/dev/./urandom -cp jdbcrunner-1.3-nojdbc.jar:lib/ojdbc.jar JR scripts/tpcc.js -jdbcDriver oracle.jdbc.driver.OracleDriver -jdbcUrl jdbc:oracle:thin:@{{ SCAN_NAME }}:1521/{{ PDBNAME }}"
    args:
      chdir: "~/jdbcrunner"
    when: inventory_hostname == groups["client"][0]
    register: tpcc_result
    tags:
      - jdbcrunner
      - tpcc_exec

  - debug: var=tpcc_result.stdout_lines
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - tpcc_exec
