---
  - name: "set targe(HA)"
    set_fact:
      TARGET: "{{ SCAN_NAME }}"
    when: dbca != 'single'
    tags:
      - jdbcrunner
      - installjdbcrunner
      - snapper

  - name: "set target(SINGLE)"
    set_fact:
      TARGET:  '{{ hostvars[groups["dbserver"][0]]["ansible_" + VXLAN_DEV ].ipv4.address }}'
    when: dbca == 'single'  
    tags:
      - jdbcrunner
      - installjdbcrunner
      - snapper
 
  - name: "set snapper measuretime"
    set_fact:
      snapper_measuretime:  '{{ ( TPCC_MEASURETIME + TPCC_WARMUPTIME )|int}}'
    tags:
      - jdbcrunner
      - installjdbcrunner
      - snapper

  - name: "install jdbcrunner dependency library"
    become: yes
    dnf:
      name:
        - git
        - ant
      state: latest
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - installjdbcrunner

  - name: "create createuser.sh"
    become: yes
    become_user: oracle
    template: 
      src: createuser.sh.j2 
      dest: "~/createuser.sh"
      mode: 0755
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner
      - installjdbcrunner

  - name: "createuser"
    become: yes
    become_user: oracle
    shell: bash -x ./createuser.sh
    args:
      chdir: "~/"
    when: inventory_hostname == groups["dbserver"][0]
    register: createuser_result
    tags:
      - jdbcrunner
      - installjdbcrunner

  - debug: var=createuser_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner
      - installjdbcrunner
      
  - name:
    git:
      repo: https://github.com/sh2/jdbcrunner.git
      dest: "~/jdbcrunner"
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner

  - name: "unzip jdbcdriver"
    local_action: shell {{ UNZIP }} /media/{{ GRID_MEDIA }} {{ JDBCDRIVER }}
    args:
      creates: "/tmp/{{ JDBCDRIVER }}"
      executable: /bin/bash
      chdir: /tmp
    run_once: true
    when: inventory_hostname == groups["client"][0] and MEDIA_COPY is defined and MEDIA_COPY !=""
    tags:
      - jdbcrunner
      
  - name: "copy jdbcdriver"
    copy:
      src: "/tmp/{{ JDBCDRIVER }}"
      dest: "~/jdbcrunner/lib/ojdbc.jar"
    when: inventory_hostname == groups["client"][0] and MEDIA_COPY is defined and MEDIA_COPY !=""
    tags:
      - jdbcrunner

  - name: ant
    shell: /usr/bin/ant && touch ant.txt
    args:
      chdir: "~/jdbcrunner"
      creates: ant.txt
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner

  - name: load tpcc data
    shell: "/usr/bin/java -Djava.security.egd=file:/dev/./urandom -cp jdbcrunner-1.3-nojdbc.jar:lib/ojdbc.jar JR scripts/tpcc_load.js -jdbcDriver oracle.jdbc.driver.OracleDriver -jdbcUrl jdbc:oracle:thin:@{{ TARGET }}:1521/{{ PDBNAME }} -jdbcUser {{ TPCCUSER }} -jdbcPass {{ TPCC_PASSWORD }}"
    args:
      chdir: "~/jdbcrunner"
    when: inventory_hostname == groups["client"][0]
    register: tpccload_result
    tags:
      - jdbcrunner
      - exectpcc

  - debug: var=tpccload_result.stdout_lines
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - exectpcc

  - name: Download snapper
    become: yes
    become_user: oracle
    get_url:
      url: https://raw.githubusercontent.com/tanelpoder/tpt-oracle/master/snapper.sql
      dest: "~/snapper.sql"
      mode: '0775'
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner
      - snapper

  - name: execute snapper
    become: yes
    become_user: oracle
    shell:
      cmd: |
        export ORACLE_SID=`ps -ef | grep pmon  | grep -v grep | awk -F '_' '{print $3}'`
        source ~/.bash_profile
        sqlplus 'sys/{{ SYSPASSWORD }}@{{ TARGET }}:1521/{{ DBNAME }} as sysdba' <<'EOF'
        spool snapper.log
        @snapper ash {{ snapper_measuretime }} 1 all
        spool off
        exit
        EOF
    args:
      chdir: "~/"
    when: inventory_hostname == groups["dbserver"][0]
    #register: snapper_result
    async: 3600
    poll: 0
    tags:
      - jdbcrunner
      - snapper

#  - debug: var=snapper_result.stdout_lines
#    when: inventory_hostname == groups["dbserver"][0]
#    tags:
#      - jdbcrunner
#      - snapper

  - name: exec tpcc
    shell: "/usr/bin/java -Djava.security.egd=file:/dev/./urandom -cp jdbcrunner-1.3-nojdbc.jar:lib/ojdbc.jar JR scripts/tpcc.js  -measurementTime {{ TPCC_MEASURETIME }} -warmupTime {{ TPCC_WARMUPTIME }} -jdbcDriver oracle.jdbc.driver.OracleDriver -jdbcUrl jdbc:oracle:thin:@{{ TARGET }}:1521/{{ PDBNAME }}  -jdbcUser {{ TPCCUSER }} -jdbcPass {{ TPCC_PASSWORD }}"
    args:
      chdir: "~/jdbcrunner"
    when: inventory_hostname == groups["client"][0]
    register: tpcc_result
    tags:
      - jdbcrunner
      - exectpcc
      - snapper


  - debug: var=tpcc_result.stdout_lines
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - exectpcc
      - snapper


  - name: cat snapper.log
    become: yes
    become_user: oracle
    shell: cat snapper.log
    args:
      chdir: "~/"
    when: inventory_hostname == groups["dbserver"][0]
    register: snapper_result
    tags:
      - jdbcrunner
      - snapper

  - debug: var=snapper_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner
      - snapper
